/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.application.forms;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.util.UIScale;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import main.application.Application;
import main.model.User;
import main.service.AuthService;
import main.util.Dialog;
import main.util.validation.Validation;
import main.util.validation.ValidationItem;
import main.util.validation.rule.RuleNotEmpty;

/**
 *
 * @author aldes
 */
public class LoginForm extends javax.swing.JPanel {
    
    private AuthService authService = new AuthService();
    
    private final User authUser;

    /**
     * Creates new form DefaultForm
     */
    public LoginForm(User authUser) {
        this.authUser = authUser;
        
        initComponents();
        
        login.putClientProperty(FlatClientProperties.STYLE, ""
                + "background:$Login.background;"
                + "arc:20;"
                + "border:50,20,0,20");
        
        groupUsername.setTitleText("Username");
        groupPassword.setTitleText("Password");
        
        lbTitle.setText("Selamat Datang");
        lbTitle.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h1.font");
        
        lbSubTitle.setText(
                String.format("<html><body style=\"text-align: center;text-justify:inter-word;\">%s</body></html>", "Silakan masukkan username dan password untuk melanjutkan")
        );
        lbSubTitle.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h2");
        
        login.setPreferredSize(new java.awt.Dimension(UIScale.scale(400), UIScale.scale(450)));
        jPanel1.setPreferredSize(new java.awt.Dimension(UIScale.scale(250), UIScale.scale(100)));
        jPanel2.setPreferredSize(new java.awt.Dimension(UIScale.scale(250), UIScale.scale(100)));
        jPanel3.setPreferredSize(new java.awt.Dimension(UIScale.scale(250), UIScale.scale(150)));
        
        initInputEvent();
    }
    
    private void initInputEvent() {
        ((JPasswordField) groupPassword.getInputField()).addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    login();
                }
            }
            
        });
    }
    
    private void login() {
        try {
            Validation formValidation = new Validation()
                    .addItem(new ValidationItem("Username", groupUsername.getInputField())
                            .addRule(new RuleNotEmpty()))
                    .addItem(new ValidationItem("Password", groupPassword.getInputField())
                            .addRule(new RuleNotEmpty()));
            
            if (!formValidation.validate()) {
                throw new Exception(formValidation.getErrorMessageString());
            }
            
            User user = authService.attempt(groupUsername.getInputValue(), groupPassword.getInputValue());
            
            Application.login();
            Application.setAuthUser(user);
            
            ((JTextField) groupUsername.getInputField()).setText(null);
            ((JPasswordField) groupPassword.getInputField()).setText(null);
        } catch (Exception ex) {
            Dialog dialog = new Dialog("Perhatian");
            dialog.setMessageType(JOptionPane.ERROR_MESSAGE);
            dialog.setMessage(ex.getMessage());
            dialog.setOptionType(JOptionPane.DEFAULT_OPTION);
            dialog.show(this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbSubTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        groupUsername = new main.application.components.TextInputGroup();
        groupPassword = new main.application.components.PasswordInputGroup();
        jPanel1 = new javax.swing.JPanel();
        cmdLogin = new javax.swing.JButton();

        net.miginfocom.swing.MigLayout migLayout1 = new net.miginfocom.swing.MigLayout();
        migLayout1.setColumnConstraints("[center]");
        migLayout1.setRowConstraints("[center]");
        migLayout1.setLayoutConstraints("fill");
        setLayout(migLayout1);

        login.setPreferredSize(new java.awt.Dimension(400, 450));
        net.miginfocom.swing.MigLayout migLayout2 = new net.miginfocom.swing.MigLayout();
        migLayout2.setLayoutConstraints("wrap,fillx");
        migLayout2.setColumnConstraints("[center]");
        login.setLayout(migLayout2);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Title");
        lbTitle.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel2.add(lbTitle, java.awt.BorderLayout.PAGE_START);

        lbSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSubTitle.setText("Subtitle");
        lbSubTitle.setPreferredSize(new java.awt.Dimension(250, 70));
        jPanel2.add(lbSubTitle, java.awt.BorderLayout.CENTER);

        login.add(jPanel2);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 150));

        groupUsername.setPreferredSize(new java.awt.Dimension(250, 60));
        jPanel3.add(groupUsername);

        groupPassword.setPreferredSize(new java.awt.Dimension(250, 60));
        jPanel3.add(groupPassword);

        login.add(jPanel3);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 100));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        cmdLogin.setText("Login");
        cmdLogin.setPreferredSize(new java.awt.Dimension(200, 35));
        cmdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoginActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLogin);

        login.add(jPanel1);

        add(login);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoginActionPerformed
        login();
    }//GEN-LAST:event_cmdLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdLogin;
    private main.application.components.PasswordInputGroup groupPassword;
    private main.application.components.TextInputGroup groupUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbSubTitle;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel login;
    // End of variables declaration//GEN-END:variables
}
