package main.application.forms;

import com.formdev.flatlaf.util.UIScale;
import java.awt.Component;
import java.io.File;
import java.net.URL;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import main.application.Application;
import main.menu.Menu;
import main.menu.MenuItem;
import main.menu.MenuType;
import main.model.User;
import main.util.Database;
import main.util.Dialog;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author aldes
 */
public class MainForm extends javax.swing.JPanel {

    private final User authUser;

    /**
     * Creates new form DefaultForm
     *
     * @param authUser
     */
    public MainForm(User authUser) {
        this.authUser = authUser;

        initComponents();
        init();
    }

    private void init() {
        int menuWidth = UIScale.scale(280);

        initMenuEvent();

        add(menu, "west, wmin " + menuWidth);
        add(panelBody, "grow");
    }

    private void initMenuEvent() {
        menu.addEvent((int menuIndex) -> {
            MenuItem item = (MenuItem) Menu.menus[menuIndex];

            if (item.getType().equals(MenuType.LOGOUT)) {
                Application.logout();

                return;
            }

            Object com = item.getMenu();

            if (item.getType().equals(MenuType.BUTTON_REPORT)) {
                showReport((String) com);

                return;
            }

            if (com != null && com instanceof JPanel) {
                showForm((JPanel) com);
            }
        });
    }

    public void setSelectedMenu(int menuIndex) {
        menu.setSelectedMenu(menuIndex);
    }

    public void showForm(Component component) {
        panelBody.removeAll();
        panelBody.add(component);
        panelBody.repaint();
        panelBody.revalidate();
    }

    private void showReport(String name) {
        try {
            File file = new File("src/resource/report/" + name + ".jrxml");
            String sourcePath = file.getAbsolutePath();

            Database db = Database.getInstance();
            db.connect();

            JasperReport jr = JasperCompileManager.compileReport(sourcePath);

            Map<String, Object> params = new HashMap<>();
            params.put(JRParameter.REPORT_LOCALE, new Locale("id", "ID"));

            JasperPrint jp = JasperFillManager.fillReport(
                    jr,
                    params,
                    db.getConnection()
            );
            
            if (jp.getPages().isEmpty()) {
                Dialog dialog = new Dialog("Perhatian");
                dialog.setMessage("Laporan kosong");
                dialog.setMessageType(JOptionPane.INFORMATION_MESSAGE);
                dialog.setOptionType(JOptionPane.DEFAULT_OPTION);
                dialog.show(getRootPane());
                
                return;
            }

            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            System.err.println("Tidak dapat melihat report " + name);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBody = new javax.swing.JPanel();
        menu = new main.menu.Menu();

        panelBody.setLayout(new java.awt.BorderLayout());

        net.miginfocom.swing.MigLayout migLayout1 = new net.miginfocom.swing.MigLayout();
        migLayout1.setLayoutConstraints("fill");
        migLayout1.setColumnConstraints("[grow,fill]");
        setLayout(migLayout1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.menu.Menu menu;
    private javax.swing.JPanel panelBody;
    // End of variables declaration//GEN-END:variables
}
